# Interoperability with non functional code using fp-ts

# fp-ts 与 非函数式代码的互操作

Sometimes you are forced to interoperate with code not written in a functional style, let's see how to deal with it.

当碰到需要与非函数式代码互操作的场景，看看如何来处理。

## Sentinels

## 哨兵（Maybe: None | Just）

Use case: an API that may fail and returns a special value of the codomain.

Use case: 一个返回可能存在的值的包装类型。

Example: **Array.prototype.findIndex**

Solution: **Option**

```ts
import { Option, none, some } from 'fp-ts/lib/Option'

function findIndex<A>(as: Array<A>, predicate: (a: A) => boolean): Option<number> {
  const index = as.findIndex(predicate)
  return index === -1 ? none : some(index)
}
```

**[译注]: 可能有值的情况，如过有值，使用 some 方法包装，没值直接返回 none，返回值标注 Option 类型**

## **undefined** and **null**

Use case: an API that may fail and returns **undefined** (or **null**).

Use case: 一个包装 **undefined** (或 **null**) 错误的处理。

Example: **Array.prototype.find**

Solution: **Option**, **fromNullable**

```ts
import { Option, fromNullable } from 'fp-ts/lib/Option'

function find<A>(as: Array<A>, predicate: (a: A) => boolean): Option<A> {
  return fromNullable(as.find(predicate))
}
```

**[译注]: 可能为空值的情况使用 fromNullable 方法包装，返回 Option 类型**

## Exceptions

## 异常处理

Use case: an API that may throw.

Use case: 可能 throw error 的处理。

Example: **JSON.parse**

Solution: **Either**, **tryCatch**

```ts
import { Either, tryCatch } from 'fp-ts/lib/Either'

function parse(s: string): Either<Error, unknown> {
  return tryCatch(() => JSON.parse(s), reason => new Error(String(reason)))
}
```

**[译注]: 可能为抛出异常，使用 tryCatch 方法包装后返回 Either 类型**

## Random values

## 随机值

Use case: an API that returns a non deterministic value.

Use case: 不确定值的处理。

Example: **Math.random**

Solution: **IO**

```ts
import { IO } from 'fp-ts/lib/IO'

const random: IO<number> = () => Math.random()
```

**[译注]: 需要在运行期计算得到的值，同副作用，返回一个 IO 类型**

## Synchronous side effects

## 有副作用的同步操作

Use case: an API that reads and/or writes to a global state.

Use case: 读写全局状态的处理。

Example: **localStorage.getItem**

Solution: **IO**

```ts
import { Option, fromNullable } from 'fp-ts/lib/Option'
import { IO } from 'fp-ts/lib/IO'

function getItem(key: string): IO<Option<string>> {
  return () => fromNullable(localStorage.getItem(key))
}
```

**[译注]: 有副作用，结果可能为空值的情况使用 fromNullable 方法包装，返回 IO<Option> 类型**

Use case: an API that reads and/or writes to a global state and may throw.

Use case: 读写全局状态并可能抛错的处理。

Example: **readFileSync**

Solution: **IOEither**, **tryCatch**

```ts
import * as fs from 'fs'
import { IOEither, tryCatch } from 'fp-ts/lib/IOEither'

function readFileSync(path: string): IOEither<Error, string> {
  return tryCatch(() => fs.readFileSync(path, 'utf8'), reason => new Error(String(reason)))
}
```

**[译注]: 有副作用，需要进行错误处理的情况使用 tryCatch 方法包装，返回 IOEither 类型**

## Asynchronous side effects

## 有副作用的异步操作

Use case: an API that performs an asynchronous computation.

Use case: 异步计算的处理

Example: reading from standard input

Example: 读取标准输入

Solution: **Task**

```ts
import { createInterface } from 'readline'
import { Task } from 'fp-ts/lib/Task'

const read: Task<string> = () =>
  new Promise<string>(resolve => {
    const rl = createInterface({
      input: process.stdin,
      output: process.stdout
    })
    rl.question('', answer => {
      rl.close()
      resolve(answer)
    })
  })
```

**[译注]: 有副作用的异步操作返回 Task 类型**

Use case: an API that performs an asynchronous computation and may reject.

Use case: 可能失败的异步计算

Example: **fetch**

Solution: **TaskEither**, **tryCatch**

```ts
import { TaskEither, tryCatch } from 'fp-ts/lib/TaskEither'

function get(url: string): TaskEither<Error, string> {
  return tryCatch(
    () => fetch(url).then(res => res.text()),
    reason => new Error(String(reason))
  )
}
```

**[译注]: 有副作用的异步操作，需要错误处理，使用 tryCatch 包装后返回 TaskEither 类型**
